development:
  adapter: postgresql
  encoding: unicode
  database: valorize_production
  pool: 5
  username: ruby
  password: ruby

production:
  adapter: postgresql
  encoding: unicode
  database: valorize_production
  pool: 5
  username: ruby
  password: ruby